In [80]:
import numpy as np


#creating a one dimensional array 
array_a = np.array([1,2,3])

#two dimensional array
array_b = np.array([[1,2,3],[4,5,6]])

#three dimensional array
array_c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [81]:
print(array_a)
array_a.dtype

[1 2 3]


dtype('int32')

In [82]:
print(array_b)
array_b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int32')

In [83]:
print(array_c)
array_c.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int32')

In [84]:
new_arr=np.array([[1,2,3],[4,5,6]])
array = new_arr.reshape(3,2)

print(f"normal array : {new_arr}\n")
print(f"after shaped array : {array}\n")
print(f"indexing the array :",array[1,0])

normal array : [[1 2 3]
 [4 5 6]]

after shaped array : [[1 2]
 [3 4]
 [5 6]]

indexing the array : 3


In [85]:
#difference between normal and numpy array
nor_arr = [1,2,3,4,5,6,'hello world']

np_arr = np.array([1,2,3,'hello world'])

In [86]:
print(f"if we add a string is normal array is only the string to string : {nor_arr}\n")
print(f"but the numpy array is take to every thing to string in the array : {np_arr}")

if we add a string is normal array is only the string to string : [1, 2, 3, 4, 5, 6, 'hello world']

but the numpy array is take to every thing to string in the array : ['1' '2' '3' 'hello world']


In [87]:
#zeros,ones,full,random in the numpy

Array_a = np.zeros((3,3))
print(f"zeros array\n{Array_a}\n")

Array_b = np.ones((3,3))
print(f"ones array\n{Array_b}\n")

Array_c = np.full((3,3),5)
print(f"full array \n{Array_c}\n")

Array_d=np.random.random((4,5))
print(f"random fill with numbers \n{Array_d}\n")

zeros array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

ones array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

full array 
[[5 5 5]
 [5 5 5]
 [5 5 5]]

random fill with numbers 
[[0.87720197 0.20558465 0.17694169 0.82703407 0.94350348]
 [0.51532037 0.14573088 0.11642546 0.32373692 0.8161474 ]
 [0.02559736 0.8852884  0.81712484 0.78066722 0.15396292]
 [0.99134939 0.14721041 0.66977647 0.7245711  0.09893381]]

